### ISSUE TITLE
Checklist for things due by 8 Nov

### ISSUE THREAD

**Issue by XXJJXJ** [AY2122S1-CS2103T-T10-2/tp#221]
### **Team based deadlines**:
- [x] Product:
Do a release on GitHub, tagged appropriately e.g., v1.4 or v1.4b.
Upload the jar file to LumiNUS.
File name: [team ID][ProductName].jar e.g. [CS2103T-T10-2][Managera].jar

- [x] Source Code: 
Push the code to GitHub and tag with the version number. 

- [x] User Guide: Convert to pdf and upload to LumiNUS. (Separate submissions for both CS2101 and CS2103T)
File name: [TEAM_ID][ProductName]UG.pdf e.g.[CS2103T-T10-2][Managera]UG.pdf
Left to do:

- [x] Developer Guide: submission is similar to the UG
File name: [TEAM_ID][ProductName]DG.pdf e.g. [CS2103T-T10-2][Managera]DG.pdf
Left to do:

- [x] Product Website: (Double check again on Sunday 7 Nov)
Update website (home page,Ui.png, AboutUs.md etc.) on GitHub. Ensure the website is auto-published.

- [x] Submit the demo video **(By 10 Nov)** [More information](https://nus-cs2103-ay2122s1.github.io/website/schedule/week13/project.html#4-submit-the-demo-video-wed-nov-10th-2359)

### **Individual**:
- [x] Project Portfolio Page (PPP):
PDF file: submission is similar to the UG
File name: [TEAM_ID][Your full Name as Given in LumiNUS]PPP.pdf e.g.[CS2103T-T10-2][Tom]PPP.pdf
